<a href="https://colab.research.google.com/github/AkiBae4891/AkiBae4891.github.io/blob/master/La_Teran_Evans_LS_DS5_131_Statistics_Probability_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 1 Sprint 3 Assignment 1*

# Apply the t-test to real data

Your assignment is to determine which issues have "statistically significant" differences between political parties in this [1980s congressional voting data](https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records). The data consists of 435 instances (one for each congressperson), a class (democrat or republican), and 16 binary attributes (yes or no for voting for or against certain issues). Be aware - there are missing values!

Your goals:

1. Load and clean the data (or determine the best method to drop observations when running tests)
2. Using hypothesis testing, find an issue that democrats support more than republicans with p < 0.01
3. Using hypothesis testing, find an issue that republicans support more than democrats with p < 0.01
4. Using hypothesis testing, find an issue where the difference between republicans and democrats has p > 0.1 (i.e. there may not be much of a difference)

Note that this data will involve *2 sample* t-tests, because you're comparing averages across two groups (republicans and democrats) rather than a single group against a null hypothesis.

Stretch goals:

1. Refactor your code into functions so it's easy to rerun with arbitrary variables
2. Apply hypothesis testing to your personal project data (for the purposes of this notebook you can type a summary of the hypothesis you formed and tested)

In [0]:
# import stuff
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import style
from scipy.stats import ttest_ind, ttest_ind_from_stats, ttest_rel
from scipy.stats import ttest_1samp


In [4]:
# read file and add column names 
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data'
                , names=["party", "handicappedInfants", "waterProject", "budget", "physicianFee", "elsalvador",
                                "religiousSchool", "satTest", "nicaraguanAid", "mxMissile", "immigration", "synfuels",
                                "education", "superfund", "crime", "dutyFree", "southafricaExport"])
print(df.shape)
df.head()

(435, 17)


party handicappedInfants waterProject  ... crime dutyFree southafricaExport
0  republican                  n            y  ...     y        n                 y
1  republican                  n            y  ...     y        n                 ?
2    democrat                  ?            y  ...     y        n                 n
3    democrat                  n            y  ...     n        n                 y
4    democrat                  y            y  ...     y        y                 y

[5 rows x 17 columns]

In [5]:
# Change yes, no values into 1, 0 values 

df2 = df.replace({'y': 1, 'n': 0, '?': -1})
df2.head()

party  handicappedInfants  ...  dutyFree  southafricaExport
0  republican                   0  ...         0                  1
1  republican                   0  ...         0                 -1
2    democrat                  -1  ...         0                  0
3    democrat                   0  ...         0                  1
4    democrat                   1  ...         1                  1

[5 rows x 17 columns]

In [0]:
# Sep the 2 parties 

rep = df2[df2['party'] == 'republican']

dem = df2[df2['party'] == 'democrat']

In [7]:
df2.head()

party  handicappedInfants  ...  dutyFree  southafricaExport
0  republican                   0  ...         0                  1
1  republican                   0  ...         0                 -1
2    democrat                  -1  ...         0                  0
3    democrat                   0  ...         0                  1
4    democrat                   1  ...         1                  1

[5 rows x 17 columns]

In [6]:
# test

dem['handicappedInfants'].value_counts()

 1    156
 0    102
-1      9
Name: handicappedInfants, dtype: int64

In [7]:
dem['handicappedInfants'].isnull().sum()

0

In [8]:
rep['handicappedInfants'].value_counts()

 0    134
 1     31
-1      3
Name: handicappedInfants, dtype: int64

In [9]:
rep['handicappedInfants'].isnull().sum()

0

In [8]:
# t test 
from scipy.stats import ttest_1samp
ttest_1samp(dem['handicappedInfants'], 0.5)

Ttest_1sampResult(statistic=1.4696201823440125, pvalue=0.14284638421776033)

In [9]:
# SA means 
print("Democrat Support: ", dem['southafricaExport'].mean())
print("Republican Support: ", rep['southafricaExport'].mean())

Democrat Support:  0.3408239700374532
Republican Support:  0.44047619047619047


In [10]:
ttest_ind(dem['southafricaExport'], rep['southafricaExport'])

Ttest_indResult(statistic=-1.1971362701747064, pvalue=0.23190842882410834)

In [16]:
# Find out Who supports budget more
# Democrats support budget more 
contingency_tableB = pd.crosstab(df2["party"],df2["budget"])
print('contingency_table :-\n',contingency_tableB)

contingency_table :-
 budget      -1    0    1
party                   
democrat     7   29  231
republican   4  142   22


In [17]:
# Find out Who supports religiousSchool more
# Republicans support religiousSchool more 
contingency_tableR = pd.crosstab(df2["party"],df2["religiousSchool"])
print('contingency_table :-\n',contingency_tableR)

contingency_table :-
 religiousSchool  -1    0    1
party                        
democrat          9  135  123
republican        2   17  149


In [18]:
# Observed Values
Observed_Values = contingency_tableB.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[  7  29 231]
 [  4 142  22]]


In [19]:
# Observed Values
Observed_Values = contingency_tableR.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[  9 135 123]
 [  2  17 149]]


In [20]:
no_of_rows=len(contingency_tableB.iloc[0:2,0])
no_of_columns=len(contingency_tableB.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [21]:
no_of_rows=len(contingency_tableR.iloc[0:2,0])
no_of_columns=len(contingency_tableR.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1
